/**
 * Generated by scripts/process-demos.mjs. Do not edit by hand.
 *
 * Filenames carry a content hash so that a re-encode publishes a new URL. These are
 * served immutable, and reusing a name left visitors watching a cached copy of a clip
 * that had already been replaced in the repository.
 */
export const demos = {
  estudia: {"src":"/demos/estudia.71417c62.mp4","poster":"/demos/estudia.71417c62-poster.webp","width":1000,"height":626},
  exposure: {"src":"/demos/exposure.d192e7da.mp4","poster":"/demos/exposure.d192e7da-poster.webp","width":1000,"height":626},
  kepler: {"src":"/demos/kepler.61699eca.mp4","poster":"/demos/kepler.61699eca-poster.webp","width":1000,"height":626},
  mipeso: {"src":"/demos/mipeso.c265705f.mp4","poster":"/demos/mipeso.c265705f-poster.webp","width":1000,"height":626},
  'momentum-investor': {"src":"/demos/momentum-investor.cf29232e.mp4","poster":"/demos/momentum-investor.cf29232e-poster.webp","width":1000,"height":626},
  oscilion: {"src":"/demos/oscilion.9044e9f2.mp4","poster":"/demos/oscilion.9044e9f2-poster.webp","width":1000,"height":626},
  tickerlens: {"src":"/demos/tickerlens.dc0c11b7.mp4","poster":"/demos/tickerlens.dc0c11b7-poster.webp","width":1000,"height":626},
  tvindicators: {"src":"/demos/tvindicators.edd3bff4.mp4","poster":"/demos/tvindicators.edd3bff4-poster.webp","width":1000,"height":626},
} as const;
